language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - hhvm
  - nightly

matrix:
  allow_failures:
    php:
      - hhvm
      - nightly

install:
  - composer self-update
  - composer install --ignore-platform-reqs

notifications:
  email: change
